title: Geylang Methodist School (Secondary)
url: https://geylangmethodistsec.moe.edu.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#1f0cf6"
  secondary-color: "#3535fc"
  media-colors:
    - title: media-color-one
      color: "#1711f5"
    - title: media-color-two
      color: "#1d1df1"
    - title: media-color-three
      color: "#f65519"
    - title: media-color-four
      color: "#1c16fa"
    - title: media-color-five
      color: "#f1f70c"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dnskg7mp0u9ot.amplifyapp.com
prod: https://master.dnskg7mp0u9ot.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: news-and-events
